### _config.yml
### jekyll config for kb3c.github.io
### 2021, polarysekt

### theme: hacker

title:          "kb3c.uX WEB"
subtitle:       "aggregated holdings"
motto:          "for to make better all of the things!"
logo:     "/assets/img/kb3cux-headerlogo-2022-softneon.png"
backsplash: "/assets/img/2022-kb3c-backsplash.png"
maintainer:     "polaR"
baseurl:        "/"
url:            ""

timezone: America/Chicago
future: false


# Syntax Highlighting
highlighter:        rouge
markdown:           kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []


#The default permalink for articles
permalink: /news/:title

collections:
    members:
        output: true
        permalink: /members/:name

# What to include/exclude from parsing
include:
  - .htaccess
exclude:
  - .gitignore
  - .directory
  - .vscode
  - package.json
  - package-lock.json
  - yarn.json
  - build/
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - vendor
  - _site
  - .vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README
  - Makefile
