### _config.yml
### jekyll config for kb3c.github.io
### 2021, polarysekt

title: kb3c.uX
subtitle: collective holdings aggregation
description: a minimal index of constituents
author: polarysekt
baseurl: "/"
url: ""


logo: assets/img/logo-grid-0.png

timezone: America/Chicago
future: false



# Syntax Highlighting
highlighter:        rouge
markdown:           kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []
