### _config.yml
### jekyll config for kb3c.github.io
### 2021, polarysekt

### theme: hacker

title: kb3c.uX
subtitle: collective holdings aggregation
description: a minimal index of constituents
author: polarysekt
baseurl: "/"
url: ""

owner:
  email:           polarysekt@protonmail.com
  github:          polarysekt
  stackexchange:   4801256
  youtube:         polarysekt
  soundcloud:      polarysekt

github_username:    polarysekt

logo: assets/img/logo-grid-0.png

timezone: America/Chicago
future: false


# Syntax Highlighting
highlighter:        rouge
markdown:           kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []


The default permalink for articles
permalink: /articles/:title

#collections_dir:

collections:
  characters:
    output: true
    permalink: /character/:name
  reference:
    output: true
    permalink: /reference/:name
  vendor:
    output: true
    permalink: /3rdparty/:name
  pinned:
    output: true
    permalink: /articles/:collection/:name

# What to include/exclude from parsing
include:
  - .htaccess
exclude:
  - .gitignore
  - .directory
  - .vscode
  - package.json
  - package-lock.json
  - yarn.json
  - build/
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - vendor
  - _site
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README
  - Makefile
